# Generated by Django 4.1.1 on 2023-02-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_newuser_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.BooleanField(default=False)),
                ('clutch', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
    ]
