# Generated by Django 4.1.1 on 2023-02-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagedpart',
            old_name='Car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='damagedpart',
            old_name='clutch',
            new_name='hood',
        ),
    ]
