# Generated by Django 4.1.1 on 2023-02-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_team', '0002_rename_car_damagedpart_car_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamagedPart',
        ),
    ]
