# Generated by Django 4.1.1 on 2023-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='min_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='yard_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
