# Generated by Django 4.1.1 on 2023-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_damagedparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='apron',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='battery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='clutch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='door',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='front_bumber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='gerabox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='head_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='hood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='pillars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='steering_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='wind_shield',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DamagedParts',
        ),
    ]
