# Generated by Django 4.1.1 on 2023-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_car_air_bag_car_apron_car_battery_car_clutch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img1',
            field=models.ImageField(default=0, upload_to='car_pics'),
            preserve_default=False,
        ),
    ]
