# Generated by Django 4.1.1 on 2023-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_car_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img1',
            field=models.ImageField(upload_to='car'),
        ),
    ]
