# Generated by Django 4.1.1 on 2023-02-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_car_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
