# Generated by Django 4.1.1 on 2023-02-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_car_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='battery',
            field=models.BooleanField(default=False),
        ),
    ]
