# Generated by Django 4.1.1 on 2023-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_car_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img1',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
