# Generated by Django 4.1.1 on 2023-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_car_img1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='img1',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=0, upload_to='car_images/'),
            preserve_default=False,
        ),
    ]
