# Generated by Django 4.1.1 on 2023-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_car_img1_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(default=0, upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(default=0, upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(default=0, upload_to='car_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image5',
            field=models.ImageField(default=0, upload_to='car_images/'),
            preserve_default=False,
        ),
    ]
