# Generated by Django 4.1.1 on 2023-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_car_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
