# Generated by Django 4.1.1 on 2023-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_price_auction_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='car_name',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
