# Generated by Django 4.1.1 on 2023-02-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auction_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='largest_bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
