# Generated by Django 4.1.1 on 2023-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_auction_largest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user_name',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
