# Generated by Django 4.1.1 on 2023-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auction_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user_name',
            field=models.CharField(max_length=25),
        ),
    ]
