# Generated by Django 4.1.1 on 2023-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_auction_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user_phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
