# Generated by Django 4.1.1 on 2023-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auction_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='user_phone',
            new_name='phone',
        ),
    ]
