# Generated by Django 4.1.1 on 2023-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_user_phone_auction_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sold_or_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
