# Generated by Django 4.1.1 on 2023-02-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auction_sold_or_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='closed_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('car_name', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('bid_amount', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('deal_closed', models.IntegerField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='sold_or_no',
            field=models.IntegerField(default=False),
        ),
    ]
