# Generated by Django 4.1.1 on 2023-02-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_closed_deals_alter_auction_sold_or_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='display_or_not',
            field=models.BooleanField(default=0),
        ),
    ]
