# Generated by Django 4.1.1 on 2023-02-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_car_display_or_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='sold_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('car_name', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('bid_amount', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
