# Generated by Django 4.1.1 on 2023-03-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_sold_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='crain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=25)),
                ('car_number', models.IntegerField()),
                ('yard_name', models.CharField(max_length=25)),
                ('drop_out_location', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
