# Generated by Django 4.1.1 on 2023-04-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_crain'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='contact_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crain',
            name='car_number',
            field=models.CharField(max_length=25),
        ),
    ]
