# Generated by Django 4.1.1 on 2023-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_crain_contact_number_alter_crain_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='on_going',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crain',
            name='contact_number',
            field=models.IntegerField(default=False),
        ),
    ]
