# Generated by Django 4.1.1 on 2023-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_crain_on_going_alter_crain_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crain',
            name='on_going',
            field=models.IntegerField(),
        ),
    ]
