# Generated by Django 4.1.1 on 2023-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_crain_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='craindriver',
            field=models.IntegerField(default=False),
        ),
    ]
