# Generated by Django 4.1.1 on 2023-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_crain_craindriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='endinging_km',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='crain',
            name='staring_km',
            field=models.IntegerField(default=False),
        ),
    ]
