# Generated by Django 4.1.1 on 2023-04-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_crain_on_going'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crain',
            old_name='endinging_km',
            new_name='end_km',
        ),
    ]
