# Generated by Django 4.1.1 on 2023-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_endinging_km_crain_end_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crain',
            name='total_km',
            field=models.IntegerField(default=0),
        ),
    ]
