# Generated by Django 4.1.1 on 2023-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_crain_price_crain_total_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
