# Generated by Django 4.1.1 on 2023-04-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_crain_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crain_completed',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='crain_completed',
            name='end_km',
        ),
        migrations.RemoveField(
            model_name='crain_completed',
            name='on_going',
        ),
        migrations.RemoveField(
            model_name='crain_completed',
            name='staring_km',
        ),
    ]
