# Generated by Django 4.1.1 on 2023-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_crain_completed_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crain',
            name='craindriver_name',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='crain',
            name='craindriver_phonenumber',
            field=models.IntegerField(default=0),
        ),
    ]
