# Generated by Django 4.1.1 on 2023-04-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_sold_cars_crain_deliverd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_cars',
            name='crain_deliverd',
            field=models.IntegerField(default=0),
        ),
    ]
