# Generated by Django 4.1.1 on 2023-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_crain_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_cars',
            name='crain_status',
            field=models.IntegerField(default=0),
        ),
    ]
